FROM mcr.microsoft.com/playwright:v1.62.1-noble

WORKDIR /app

COPY package.json package-lock.json /app/

COPY frontend/package.json /app/frontend/

COPY packages/react-email/package.json /app/packages/react-email/

RUN npm ci

WORKDIR /app/frontend

COPY ./frontend /app/frontend
