"""add games

Revision ID: e9d7fcb4602d
Revises: fe56fa70289e
Create Date: 2026-10-05 12:29:55.414062

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e9d7fcb4602d'
down_revision = 'fe56fa70289e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('home_team', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('away_team', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('competition', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('kickoff', sa.DateTime(timezone=True), nullable=False),
    sa.Column('venue_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('venue_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'postponed', 'cancelled', 'finished', name='gamestatus'), nullable=False),
    sa.Column('source', sa.Enum('api', 'manual', name='gamesource'), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game')
    sa.Enum(name="gamestatus").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="gamesource").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
